apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      name: rails
      namespace: app
      labels:
        app: rails
    spec:
      volumes:
        - name: nginx-config-default
          configMap:
            name: nginx-config
      containers:
        - image: nginx:alpine
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-default
              mountPath: /etc/nginx/conf.d/
        - image: app:1
          name: app
          env:
            - name: DB_HOST
              value: "mysql.app"
            - name: DB_PASSWORD
              value: "password"

          # Dockefileを指定する方法？
        # railsを追加する

