apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app
spec:
  volumes:
    - name: nginx-config-default
      configMap:
        name: nginx-config
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-config-default
          mountPath: /etc/nginx/conf.d/
