apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      namespace: app
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config-default
          configMap:
            name: nginx-config
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-default
              mountPath: /etc/nginx/conf.d/
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
