apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app
spec:
  ports:
    - nodePort: 32148
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: NodePort
